<?xml version="1.0" encoding="utf-8"?><Database Name="Journal" Class="FunctionsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Journal.mdf;Integrated Security=True" SettingsObjectName="DailyWriter.My.MySettings" SettingsPropertyName="JournalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.dw_users" Member="dw_users">
    <Type Name="dw_user">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dw_journal" Member="dw_journals">
    <Type Name="dw_journal">
      <Column Name="journalID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="JournalCover" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="JournalTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="JournalDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsPassword" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>